#!/bin/sh /etc/rc.common
USE_PROCD=1
START=100
STOP=10

start_service() {
  procd_open_instance
  procd_set_param command /bin/sh -c 'while true; do /usr/bin/v2raya-ensure-bindings --quiet; sleep 20; done'
  procd_set_param respawn 3600 5 0
  procd_set_param stdout 0
  procd_set_param stderr 0
  procd_close_instance
}
